// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto
	stored.proto

It has these top-level messages:
	KnownEvents
	EventRequest
	PeerRequest
	PeerInfo
	PeerIDs
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wire "github.com/Fantom-foundation/go-lachesis/src/inter/wire"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KnownEvents struct {
	Lasts map[string]uint64 `protobuf:"bytes,1,rep,name=Lasts" json:"Lasts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *KnownEvents) Reset()                    { *m = KnownEvents{} }
func (m *KnownEvents) String() string            { return proto.CompactTextString(m) }
func (*KnownEvents) ProtoMessage()               {}
func (*KnownEvents) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KnownEvents) GetLasts() map[string]uint64 {
	if m != nil {
		return m.Lasts
	}
	return nil
}

type EventRequest struct {
	PeerID string `protobuf:"bytes,1,opt,name=PeerID" json:"PeerID,omitempty"`
	Index  uint64 `protobuf:"varint,2,opt,name=Index" json:"Index,omitempty"`
	Hash   []byte `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (m *EventRequest) Reset()                    { *m = EventRequest{} }
func (m *EventRequest) String() string            { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()               {}
func (*EventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *EventRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PeerRequest struct {
	PeerID string `protobuf:"bytes,1,opt,name=PeerID" json:"PeerID,omitempty"`
}

func (m *PeerRequest) Reset()                    { *m = PeerRequest{} }
func (m *PeerRequest) String() string            { return proto.CompactTextString(m) }
func (*PeerRequest) ProtoMessage()               {}
func (*PeerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PeerRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

type PeerInfo struct {
	ID     string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	PubKey []byte `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Host   string `protobuf:"bytes,3,opt,name=Host" json:"Host,omitempty"`
	Cert   []byte `protobuf:"bytes,4,opt,name=Cert,proto3" json:"Cert,omitempty"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PeerInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PeerInfo) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PeerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PeerInfo) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func init() {
	proto.RegisterType((*KnownEvents)(nil), "api.KnownEvents")
	proto.RegisterType((*EventRequest)(nil), "api.EventRequest")
	proto.RegisterType((*PeerRequest)(nil), "api.PeerRequest")
	proto.RegisterType((*PeerInfo)(nil), "api.PeerInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	SyncEvents(ctx context.Context, in *KnownEvents, opts ...grpc.CallOption) (*KnownEvents, error)
	GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*wire.Event, error)
	GetPeerInfo(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerInfo, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) SyncEvents(ctx context.Context, in *KnownEvents, opts ...grpc.CallOption) (*KnownEvents, error) {
	out := new(KnownEvents)
	err := grpc.Invoke(ctx, "/api.Node/SyncEvents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*wire.Event, error) {
	out := new(wire.Event)
	err := grpc.Invoke(ctx, "/api.Node/GetEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetPeerInfo(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerInfo, error) {
	out := new(PeerInfo)
	err := grpc.Invoke(ctx, "/api.Node/GetPeerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	SyncEvents(context.Context, *KnownEvents) (*KnownEvents, error)
	GetEvent(context.Context, *EventRequest) (*wire.Event, error)
	GetPeerInfo(context.Context, *PeerRequest) (*PeerInfo, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_SyncEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnownEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SyncEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/SyncEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SyncEvents(ctx, req.(*KnownEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetPeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetPeerInfo(ctx, req.(*PeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncEvents",
			Handler:    _Node_SyncEvents_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _Node_GetEvent_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _Node_GetPeerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4f, 0xef, 0xd2, 0x40,
	0x10, 0xa5, 0x7f, 0x7e, 0xbf, 0xc0, 0x14, 0x0c, 0x6e, 0x8c, 0x69, 0xea, 0xa5, 0x69, 0x62, 0xd2,
	0x83, 0xb4, 0x8a, 0x17, 0xe2, 0x15, 0x10, 0x09, 0xc6, 0x90, 0x7a, 0xf3, 0xb6, 0x94, 0x01, 0x36,
	0xc2, 0x2e, 0xee, 0x6e, 0xc1, 0xfa, 0x51, 0xfc, 0xb4, 0x66, 0xb7, 0x15, 0x89, 0x1e, 0xbc, 0xbd,
	0xf7, 0x66, 0xe6, 0xcd, 0xee, 0x1b, 0x18, 0x28, 0x94, 0x17, 0x56, 0x62, 0x76, 0x96, 0x42, 0x0b,
	0xe2, 0xd1, 0x33, 0x8b, 0xa6, 0x7b, 0xa6, 0x0f, 0xd5, 0x26, 0x2b, 0xc5, 0x29, 0x7f, 0x4f, 0xb9,
	0x16, 0xa7, 0xd1, 0x4e, 0x54, 0x7c, 0x4b, 0x35, 0x13, 0x3c, 0xdf, 0x8b, 0xd1, 0x91, 0x96, 0x07,
	0x54, 0x4c, 0xe5, 0x4a, 0x96, 0x39, 0xe3, 0x1a, 0x65, 0x7e, 0x65, 0x12, 0x73, 0xbc, 0x20, 0xd7,
	0x8d, 0x53, 0xf2, 0x03, 0x82, 0x15, 0x17, 0x57, 0x3e, 0x37, 0x9a, 0x22, 0x6f, 0xe0, 0xe1, 0x23,
	0x55, 0x5a, 0x85, 0x4e, 0xec, 0xa5, 0xc1, 0xf8, 0x45, 0x46, 0xcf, 0x2c, 0xbb, 0x6b, 0xc8, 0x6c,
	0x75, 0xce, 0xb5, 0xac, 0x8b, 0xa6, 0x33, 0x9a, 0x00, 0xfc, 0x11, 0xc9, 0x10, 0xbc, 0xaf, 0x58,
	0x87, 0x4e, 0xec, 0xa4, 0xbd, 0xc2, 0x40, 0xf2, 0x0c, 0x1e, 0x2e, 0xf4, 0x58, 0x61, 0xe8, 0xc6,
	0x4e, 0xea, 0x17, 0x0d, 0x79, 0xe7, 0x4e, 0x9c, 0x64, 0x0d, 0x7d, 0xeb, 0x5a, 0xe0, 0xb7, 0x0a,
	0x95, 0x26, 0xcf, 0xe1, 0x71, 0x8d, 0x28, 0x97, 0xb3, 0x76, 0xbc, 0x65, 0xc6, 0x61, 0xc9, 0xb7,
	0xf8, 0xfd, 0xb7, 0x83, 0x25, 0x84, 0x80, 0xff, 0x81, 0xaa, 0x43, 0xe8, 0xc5, 0x4e, 0xda, 0x2f,
	0x2c, 0x4e, 0x5e, 0x42, 0x60, 0x66, 0xfe, 0x63, 0x98, 0x7c, 0x81, 0xae, 0x45, 0x7c, 0x27, 0xc8,
	0x13, 0x70, 0x6f, 0x75, 0x77, 0x39, 0xb3, 0x33, 0xd5, 0x66, 0x85, 0xb5, 0xdd, 0xd6, 0x2f, 0x5a,
	0x66, 0xd7, 0x09, 0xa5, 0xed, 0xba, 0x5e, 0x61, 0xb1, 0xd1, 0xa6, 0x28, 0x75, 0xe8, 0x37, 0x4f,
	0x30, 0x78, 0xfc, 0xd3, 0x01, 0xff, 0x93, 0xd8, 0x22, 0x19, 0x03, 0x7c, 0xae, 0x79, 0xd9, 0x06,
	0x3b, 0xfc, 0x3b, 0xc9, 0xe8, 0x1f, 0x25, 0xe9, 0x90, 0x57, 0xd0, 0x5d, 0xa0, 0xb6, 0x94, 0x3c,
	0xb5, 0xf5, 0xfb, 0x80, 0xa2, 0x20, 0x33, 0xf7, 0x6b, 0xb4, 0xa4, 0x43, 0x5e, 0x43, 0xb0, 0x40,
	0x7d, 0xfb, 0x49, 0x63, 0x78, 0xf7, 0xff, 0x68, 0x70, 0x53, 0x4c, 0x43, 0xd2, 0xd9, 0x3c, 0xda,
	0xa3, 0xbf, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xdc, 0xd0, 0xc1, 0x4f, 0x02, 0x00, 0x00,
}
